# Generated by Django 4.1.7 on 2023-08-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('normal_image', models.ImageField(upload_to='concerts/')),
                ('png_image', models.ImageField(blank=True, null=True, upload_to='concerts/')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ticket_available', models.BooleanField()),
                ('ticket_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ConcertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='participants/')),
                ('participant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainapp.participanttype')),
            ],
        ),
        migrations.CreateModel(
            name='NostalgiaConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ticket_available', models.BooleanField()),
                ('ticket_link', models.URLField()),
                ('participants', models.ManyToManyField(related_name='nostalgia_concerts', to='Mainapp.participant')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainapp.space')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='concert_media/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainapp.concert')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainapp.concerttype'),
        ),
        migrations.AddField(
            model_name='concert',
            name='participants',
            field=models.ManyToManyField(related_name='concerts', to='Mainapp.participant'),
        ),
        migrations.AddField(
            model_name='concert',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainapp.space'),
        ),
    ]
