# Generated by Django 4.1.7 on 2023-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='participants',
            field=models.ManyToManyField(related_name='concerts_attending', to='Mainapp.participant'),
        ),
    ]
