# Generated by Django 4.1.7 on 2023-08-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_remove_nostalgiaconcert_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.IntegerField(),
        ),
    ]
