# Generated by Django 4.1.7 on 2023-08-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_alter_actualite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nostalgiaconcert',
            name='date',
            field=models.IntegerField(),
        ),
    ]
