# Generated by Django 4.1.7 on 2023-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_alter_actualite_date_alter_nostalgiaconcert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nostalgiaconcert',
            name='participants',
            field=models.ManyToManyField(related_name='nostalgia_concerts', to='Mainapp.participant'),
        ),
        migrations.AlterField(
            model_name='nostalgiaconcert',
            name='date',
            field=models.DateField(),
        ),
    ]
