# Generated by Django 4.1.7 on 2023-08-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0009_nostalgiaconcert_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nostalgiaconcert',
            name='normal_image',
            field=models.ImageField(null=True, upload_to='concerts/'),
        ),
    ]
