# Generated by Django 4.1.7 on 2023-08-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0011_media_nostalgie'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='bg_color1',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='concert',
            name='bg_color2',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
