# Generated by Django 4.1.7 on 2023-08-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0012_concert_bg_color1_concert_bg_color2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='bg_color1',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='bg_color2',
        ),
    ]
